#
# Poetry project to manage Odoo's deps with Poetry.
#
# To put together this file and the corresponding lock file from scratch:
# - start our Nix shell
# - download `odoo_14.0.20231205.tar.gz`
# - extract and `cd` into extracted dir
# - run `poetry init`
# - edit generated `pyproject.toml` to change the `packages` include
#   to `odoo` and copy over Python deps from `requirements.txt`
# - run `poetry lock`
# - copy over both `pyproject.toml` and `poetry.lock` to our Odoo
#   Nix package source dir
#

[tool.poetry]
name = "Odoo Server 14.0-20231205"
version = "14.0.20231205"
description = "Odoo Server repackaged with Poetry."
authors = ["c0c0n3"]
license = "LGPL-3.0-only"
readme = "README.md"

# The odoo_14.0.20231205.tar.gz tarball has all the Odoo code under
# the `odoo` dir, hence the below package include.
packages = [{include = "odoo"}]


[tool.poetry.dependencies]

# Our Python's version---i.e. the one we'd like to run Odoo with.
python = "^3.11"

# Deps from Odoo's `requirements.txt` in the `odoo_14.0.20231205.tar.gz`
# tarball.

Babel = "==2.9.1"
chardet = "==3.0.4"
decorator = "==4.3.0"
docutils = "==0.14"
ebaysdk = "==2.1.5"
freezegun = "==0.3.15"
gevent = "==21.8.0"
greenlet = "==1.1.2"
idna = "==2.6"
Jinja2 = "==2.11.2"
libsass = "==0.17.0"
lxml = "==4.6.5"
Mako = "==1.0.7"
MarkupSafe = "==1.1.0"
num2words = "==0.5.6"
ofxparse = "==0.21"
passlib = "==1.7.1"
Pillow = "==8.1.1"
polib = "==1.1.0"
psutil = "==5.6.6"
psycopg2 = "==2.8.5"
pydot = "==1.4.1"
python-ldap = "==3.1.0"
PyPDF2 = "==1.26.0"
pyserial = "==3.4"
python-dateutil = "==2.7.3"
pytz = "^2019.1"
pyusb = "==1.0.2"
qrcode = "==6.1"
reportlab = "==3.5.55"
requests = "==2.25.1"
urllib3 = "==1.26.5"
zeep = "==3.2.0"
python-stdnum = "==1.8"
vobject = "==0.9.6.1"
Werkzeug = "==2.0.2"
XlsxWriter = "==1.1.2"
xlwt = "1.3.*"
xlrd = "==1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
